    "let g:loaded_gzip               =  1
    "let g:loaded_tarPlugin          =  1
    "let g:loaded_zipPlugin          =  1
    "let g:loaded_2html_plugin       =  1
    "let g:loaded_rrhelper           =  1
    "let g:loaded_remote_plugins     =  1
    "let g:loaded_netrw              =  1
    "let g:loaded_netrwPlugin        =  1

"GENERAL SETTINGS
    set path+=** 
    set encoding=UTF-8 
    set nobackup nowritebackup noswapfile autowriteall 
    set tabstop=8 
    set conceallevel=2
    set wildmenu wildignorecase 
    set number relativenumber
    set clipboard+=unnamed "set the vim's clipboard to the system's clipboard
    set viminfo+=n$XDG_DATA_HOME/vim/viminfo

"KEYBINDINGS
    let mapleader=" "
    nnoremap Y y$
    nnoremap <leader>p :bn<CR>
    nnoremap <leader>n :bp<CR>
    nnoremap <leader>fe :e ~/.vim/vimrc<CR>
    nnoremap <leader>al Vgq
    "fix indetation command in visual mode
    vmap < <gv
    vmap > >gv

"COMMANDS

let g:polyglot_disabled = ['markdown']

"PLUGINS
call plug#begin('$XDG_DATA_HOME/vim/plugins')

    Plug 'dracula/vim'
    Plug 'sheerun/vim-polyglot'
    Plug 'vim-pandoc/vim-pandoc-syntax'

call plug#end()

"COLORS
    syntax on
    colorscheme dracula
    set background=dark
    set termguicolors t_Co=256
    let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
    let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
    hi! Normal ctermbg=NONE guibg=NONE

"FILETYPE
    filetype plugin on

"VIM-PANDOC
    augroup pandoc_syntax
        au! BufNewFile,BufFilePre,BufRead *.md set filetype=markdown.pandoc
    augroup END
    let g:pandoc#syntax#conceal#blacklist = ["atx", "codeblock_start", "codeblock_delim"]
