-- local cmp = require'cmp'

-- cmp.setup {
--   snippet = {
--     expand = function(args)
--       require'luasnip'.lsp_expand(args.body)
--     end
--   },
--   sources = {
--     { name = 'luasnip', option = { use_show_condition = false } },
--     { name = 'nvim_lsp', max_item_count = 10},
--     { name = 'buffer', keyword_length = 1},
--   }
-- }
