let g:loaded_netrw = 1
let g:loaded_netrwPlugin = 1
" let g:netrw_keepdir = 0
" let g:netrw_altfile = 1
" let g:netrw_winsize = 30
" let g:netrw_banner = 0
" let g:netrw_hide = 0
" let g:netrw_localcopydircmd = 'cp -r'
" let g:netrw_dirhistmax = 0
" let g:netrw_home = expand('$XDG_CACHE_HOME') . '/nvim'
