-- require('telescope').setup {
--   defaults = {
--     mappings = {
--       i = {
--         -- map actions.which_key to <C-h> (default: <C-/>)
--         -- actions.which_key shows the mappings for your picker,
--         -- e.g. git_{create, delete, ...}_branch for the git_branches picker
--         ["<C-h>"] = "which_key",
--         ["<C-s>"] = "select_horizontal",
--         ["<esc>"] = require('telescope.actions').close,
--       }
--     }
--   },
--   picker = {
--   },
-- }

-- map('n', '<leader>ff', ':Telescope find_files<CR>')
-- map('n', '<leader>fb', ':Telescope buffers<CR>')
-- map('n', '<leader>fl', ':Telescope current_buffer_fuzzy_find<CR>')
-- map('n', '<leader>f.', ':lua require("telescope.builtin").find_files({ prompt_title = "< DotFiles >", cwd = vim.env.DOTFILES, })<CR>')
-- map('n', '<leader>fn', ':lua require("telescope.builtin").find_files({ prompt_title = "< Notes >", cwd = vim.env.NOTES, })<CR>')
-- map('n', '<leader>fw', ':Telescope live_grep<CR>')
-- map('n', '<C-h>', ':Telescope help_tags<CR>')
