--require('telescope').setup{
--
--  defaults = {
--    preview = false,
--  },
--  pickers = {
--    find_files = {
--      theme = "ivy",
--    },
--    buffers = {
--      theme = "dropdown",
--    },
--    live_grep = {
--      theme = "ivy",
--    }
--  },
--  extensions = {
--  }
--}
--
