"GENERAL SETTINGS
    set path+=** 
    set encoding=UTF-8 
    set nobackup nowritebackup noswapfile autowriteall 
    set tabstop=8 
    set conceallevel=2
    set wildmenu wildignorecase 
    set number relativenumber
    set clipboard+=unnamed "set the vim's clipboard to the system's clipboard
    set viminfo+=n$XDG_DATA_HOME/vim/viminfo
"    set backspace=0
    let loaded_netrwPlugin = 1 "disabling netrw
    let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
    let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"

"KEYBINDINGS
    let mapleader=" "
    let maplocalleader=" "
    nnoremap Y y$
    nnoremap <C-c> <C-W>c
    nnoremap <C-h> <C-W>h
    nnoremap <C-j> <C-W>j
    nnoremap <C-k> <C-W>k
    nnoremap <C-l> <C-W>l
    nnoremap <leader>s :source ~/.vim/vimrc<CR>
    nnoremap <leader>p :bn<CR>
    nnoremap <leader>n :bp<CR>
    nnoremap <leader>fe :e ~/.vim/vimrc<CR>
    nnoremap <leader>Al vipgq
    nnoremap <leader>al Vgq
    nnoremap <leader>P :!open -a Typora %<CR>
    "move line in visual mode
    xnoremap K :move '<-2<CR>gv-gv 
    xnoremap J :move '>+2<CR>gv-gv
    "fix indetation command in visual mode
    vmap < <gv
    vmap > >gv

"COMMANDS

let g:polyglot_disabled = ['markdown']

"PLUGINS
call plug#begin('~/.local/share/vim/plugins')

    Plug 'dracula/vim'
    Plug 'sheerun/vim-polyglot'
    Plug 'ap/vim-css-color'
    Plug 'vim-pandoc/vim-pandoc-syntax'
    Plug 'vim-pandoc/vim-pandoc'

call plug#end()

"COLORS
    syntax on
    colorscheme dracula
    set background=dark
    set termguicolors t_Co=256

"ULTISNIP
    let g:UltiSnipsEditSplit="vertical"

"FILETYPE
    filetype plugin on

"VIM-PANDOC
    augroup pandoc_syntax
        au! BufNewFile,BufFilePre,BufRead *.md set filetype=markdown.pandoc
    augroup END
    let g:pandoc#modules#disabled = ["folding", "formatting", "completition", "spell", "menu"]  
    let g:pandoc#syntax#conceal#blacklist = ["atx", "codeblock_start", "codeblock_delim"]
