#!/bin/sh

USB_DRIVE="/Volumes/UNTITLED"
HDD="/Volumes/backup2"

check(){
    local DRIVE

    [ "$1" = "usb" ] && DRIVE="$USB_DRIVE" || DRIVE="$HDD"
    
    rsync -av --dry-run "$HOME/.ssh/" "$DRIVE/Ssh Key/" | less
    rsync -av --dry-run "$HOME/Library/Keychains/" "$DRIVE/Keychain/" | less
    rsync -av --dry-run "$DOTFILES/" "$DRIVE/Dotfiles/" | less
    rsync -av --dry-run "$DOCUMENTS/" "$DRIVE/Documents" | less
    rsync -av --dry-run "$PROJECTS/" "$DRIVE/Projects" | less
    rsync -av --dry-run "$MEDIA/" "$DRIVE/Media" | less
}

backup_to_disk(){
    check "hdd"
    printf '%b\n' "\033[1m""Do you wanna go over? [y|n]: ""\033[0m"; read -r ANSWER
    case "$ANSWER" in
         [yY])
            rsync -av --progress "$HOME/.ssh/" "$HDD/Ssh Key/"
            rsync -av --progress "$HOME/Library/Keychains/" "$HDD/Keychain/"
            rsync -av --progress "$DOTFILES/" "$HDD/Dotfiles/"
            rsync -av --progress "$DOCUMENTS/" "$HDD/Documents/"
            rsync -av --progress "$PROJECTS/" "$HDD/Projects"
            rsync -av --progress "$MEDIA/" "$HDD/Media" 
            ;;
         [nN])
            printf "Stoping...\n"
            exit
            ;;
    esac
}

backup_to_usb(){
    check "usb"
    printf '%b\n' "\033[1m""Do you wanna go over? [y|n]: ""\033[0m"; read -r ANSWER
    case "$ANSWER" in
         [yY])
            rsync -av --progress "$HOME/.ssh/" "$USB_DRIVE/Ssh Key/"
            rsync -av --progress "$HOME/Library/Keychains/" "$USB_DRIVE/Keychain/"
            rsync -av --progress "$DOTFILES/" "$USB_DRIVE/Dotfiles/"
            rsync -av --progress "$DOCUMENTS/" "$USB_DRIVE/Documents/"
            rsync -av --progress "$PROJECTS/" "$USB_DRIVE/Projects"
            rsync -av --progress "$MEDIA/" "$USB_DRIVE/Media" 
            ;;
         [nN])
            printf "Stoping...\n"
            exit
            ;;
    esac
}

while getopts "du" opt; do
    case "$opt" in
        d) backup_to_disk && exit;;
        u) backup_to_usb && exit;;
        *) exit;;
    esac
done
