#!/usr/bin/env bash

# user_filelist=''
if [[ -n "$BMK_FILE" ]]; then
  bmk_file="$BMK_FILE"
else
  bmk_file="${XDG_DATA_HOME:-$HOME/.local/share}/bmk.yaml"
fi

cat_file(){
  cat "$bmk_file" | sed 's/#.*//g' | sed '/^\s*$/d' | sed "s|~|$HOME|"
}

# make output of file more clean and managebal
parser(){
  local target=''
  [[ "$1" == 'dir' ]] && target="directories[]"
  [[ "$1" == 'files' ]] && target="files[]"
  cat_file | yq .$target
}

add_bmk(){
  echo $(pwd | sed "s|$HOME|~|") >> "$DOTFILES/data/bookmarks"
}

parser "$1"
