#!/bin/sh

user_filelist=''
 
if [ -r ~/Repos/dot/data/bookmarks ]; then
   user_filelist=$(cdscuts_list_echo ~/Repos/dot/data/bookmarks)
fi
 
echo "$system_wide_filelist\n$user_filelist" | sed '/^\s*$/d'
