#!/bin/sh

user_filelist=''
bmk_file="~/Repos/dot/data/bookmarks"
 
if [ -r "bmk_file" ]; then
   user_filelist=$(cdscuts_list_echo ~/Repos/dot/data/bookmarks)
fi
 
echo "$system_wide_filelist\n$user_filelist" | sed '/^\s*$/d'
