#!/bin/sh

alias target='find "$DOTFILES" -maxdepth 1 | fzf -m'
alias choose='find "$DOTFILES" | sed "/.git.*/ d" | fzf -m'

list_sym(){
    find "$XDG_CONFIG_HOME" "$HOME" -ls -maxdepth 1 | grep ">.*dot" | awk '{print $11 $12}' | sed "s/->//g"
}

sym_home(){
    target | xargs -I {} basename {} | xargs -I {} ln -sf "$DOTFILES/{}" "$HOME/{}"
}

sym_config(){
	target | xargs -I {} basename {} | xargs -I {} ln -sf "$DOTFILES/{}" "$XDG_CONFIG_HOME/{}"
}

edit_dot(){
    # Il comando tee duplica lo standard input non rompendo il resto 
 	choose | tee /tmp/lastdotedit | xargs $EDITOR
}

edit_last(){
    # Standard output to $EDITOR
    < /tmp/lastdotedit xargs $EDITOR 
}

remove_dot(){
    list_sym | fzf -m | xargs -I {} rm -rf {}
}

if [ $# = 0 ]; then
    list_sym && exit;
else
  while getopts "cheEr" opt; do
    case "$opt" in
      c) sym_config && exit;;
      h) sym_home && exit;;
      e) edit_dot && exit;;
      E) edit_last && exit;;
      r) remove_dot && exit;;
      *) exit
    esac
  done
fi
