#!/bin/sh

list_sym(){
    find "$XDG_CONFIG_HOME" "$HOME/.config" "$HOME" -ls -maxdepth 1 | grep ">" | grep ".dot" | awk '{print $11}'
}

sym_home(){
    find "$DOTFILES" -maxdepth 1 | fzf -m | xargs -I {} basename {} | xargs -I {} ln -sf "$DOTFILES/{}" "$HOME/{}"
}

sym_config(){
    find "$DOTFILES" -maxdepth 1 | fzf -m | xargs -I {} basename {} | xargs -I {} ln -sf "$DOTFILES/{}" "$XDG_CONFIG_HOME/{}"
}

edit_dot(){
    target=$(find "$DOTFILES" | fzf)
    $EDITOR $target && printf "%s" "$target" > /tmp/lastdotedit
}

edit_last(){
    cat "/tmp/lastdotedit" | xargs $EDITOR
}

remove_dot(){
    list_sym | fzf -m | xargs -I {} rm -rf {}
}

if [ $# = 0 ]; then
    list_sym && exit;
else
  while getopts "cheEr" opt; do
    case "$opt" in
      c) sym_config && exit;;
      h) sym_home && exit;;
      e) edit_dot && exit;;
      E) edit_last && exit;;
      r) remove_dot && exit;;
      *) exit
    esac
  done
fi
