#!/bin/sh

HDD="/Volumes/backup2"

check(){
    [ -e "$HDD" ] || exit
    rsync -av --dry-run "$HOME/.ssh/" "$HDD/Ssh Key/" | less
    rsync -av --dry-run "$HOME/Library/Keychains/" "$HDD/Keychain/" | less
    rsync -av --dry-run "$DOTFILES/" "$HDD/Dotfiles/" | less
    rsync -av --dry-run "$DOCUMENTS/" "$HDD/Documents" | less
    rsync -av --dry-run "$PROJECTS/" "$HDD/Projects" | less
    rsync -av --dry-run "$HOME/Pictures/" "$HDD/Pictures" | less
    printf '%b\n' "\033[1m""Do you wanna go over? [y|n]: ""\033[0m"; read -r ANSWER
    case "$ANSWER" in
         [yY])
             return 0
             ;;
         [nN])
             exit
             ;;
    esac
}

check || exit

rsync -av --progress "$HOME/.ssh/" "$HDD/Ssh Key/"
rsync -av --progress "$HOME/Library/Keychains/" "$HDD/Keychain/"
rsync -av --progress "$DOTFILES/" "$HDD/Dotfiles/"
rsync -av --progress "$DOCUMENTS/" "$HDD/Documents/"
rsync -av --progress "$PROJECTS/" "$HDD/Projects"
rsync -av --progress "$HOME/Pictures/" "$HDD/Pictures"

exit
