#!/bin/bash

# Check the OS
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    lynxpath=/usr/bin/lynx
elif [[ "$OSTYPE" == "darwin"* ]]; then
    lynxpath=/usr/local/bin/lynx
fi

# Useragent string to use
useragent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0) AppleWebKit/537.1 (KHTML, like Gecko) Chrome/21.0.1180.79 Safari/537.1 Lynx"

# Check if the config files exists
if [ -e "$XDG_CONFIG_HOME/lynx/lynx.cfg" ];then
    config="$XDG_CONFIG_HOME/lynx/lynx.cfg"
elif [ -e "$XDG_CONFIG_HOME/lynx/lynx.lss" ];then
    export LYNX_LSS="$XDG_CONFIG_HOME/lynx/lynx.lss"
fi

if [ ! -x "$lynxpath" ]; then
  echo "Doesn't look like lynx is installed."
  exit 1
fi

exec "$lynxpath" --useragent="$useragent" -cfg "$config" "$@"
