#!/bin/sh

read -p "Quanto è grande il tuo cazzo? (in centimetri): " LUNG
# echo "Piacere $NAME, io sono tuo padre"
if [ $LUNG == 69 ]
then 
	read -p "Ti va di scopare? [si/no]: " ANSWER
	case "$ANSWER" in 
		[sS][iI])
			echo "Da me alle 21, camera 69"
			;;
		[nN][oO])
			read -p "Scusa, com'è che ti chiamavi?: " NAME
			echo "FANCULO $NAME!"
			;;
		*)
			echo "Rispondi si o no"
			;;
	esac

else
	echo "$LUNG cm di cazzo sono veramente pochi!"
fi
