#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then 
  selected="$1" && [[ "$selected" == '.' ]] && selected="$PWD"
else
  selected=$(find ~/Projects/ ~/Repos -mindepth 1 -maxdepth 1 -type d | fzf)
fi

[[ -z "$selected" ]] && exit 0

selected_name=$(basename "$selected")
selected_name_t=${selected_name:0:8}

if [[ -n $TMUX ]]; then
  tmux switch-client -t "$selected_name_t" \
  || tmux new-session -ds "$selected_name_t" -c "$selected" \
  && tmux switch-client -t "$selected_name_t"
fi

if [[ -z $TMUX ]]; then
  tmux new-session -s "$selected_name_t" -c "$selected" \
  || tmux attach -t "$selected_name_t"
fi
