#!/usr/bin/env bash

# Select a directory listed in the bookmark file
if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(cdscuts_glob_echo | fzf)
fi

[[ -z $selected ]] && exit 1

selected_name=$(basename "$selected" | tr . _)
selected_name_t=${selected_name:0:8}
tmux_running=$(pgrep "tmux")

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name_t -c $selected
    exit 0
fi

if ! tmux has-session -t $selected_name_t 2> /dev/null; then
    tmux new-session -ds $selected_name_t -c $selected
fi

tmux switch-client -t $selected_name_t
