#!/bin/sh

# [ -x "$(which rg)" ] && GREP="rg --color never" || GREP=grep
# [ -x "$(which fd)" ] && FIND=fd || FIND=find
alias="rg --pre-glob *.md"

todo_list(){
  rg "\- \[ \]" ./*
}

todo_edit(){
  find TODO.md | xargs "$EDITOR"
}

scheduled(){
  local date=$(date +%Y)
  todo_list | rg --pre-glob "$date" "$PROJECTS" "$REPOS"
}
#
# scheduled_today(){
#   $GREP "due:<$(date +%d-%m-%Y)>" ./*
# }
#
# scheduled_tommorow(){
#   $GREP "due:<$(date -v +1d +%d-%m-%Y)>" ./*
# }

tag_search(){
  $GREP "\- \[ \].*#$1"
}

tag_list(){
  $GREP "\- \[.*\]" | $GREP -o "#\S*[a-z]" | sort -u
}

[ "$#" = 0 ] && todo_list
[ "$1" = t ] && tag_search "$2"
[ "$1" = tl ] && tag_list
[ "$1" = e ] && todo_edit
[ "$1" = s ] && scheduled
# [ "$1" = today ] && scheduled_today
# [ "$1" = tommorow ] && scheduled_tommorow

