#!/bin/sh

[ -x "$(which rg)" ] && GREP=rg || GREP=grep
[ -x "$(which fd)" ] && FIND=fd || FIND=find


todo_list(){
  $GREP "\- \[ \]" ./*
}

todo_edit(){
  [ "$FIND" = "fd" ] && FIND="fd --max-depth 1"
  $FIND TODO.md | xargs "$EDITOR"
}

scheduled(){
  $GREP "due:<.*>" ./*
}

scheduled_today(){
  $GREP "due:<$(date +%d-%m-%Y)>" ./*
}

scheduled_tommorow(){
  $GREP "due:<$(date -v +1d +%d-%m-%Y)>" ./*
}

tag_search(){
  todo_list | $GREP "#$1" ./*
}

tag_list(){
  todo_list | $GREP "^#\S*[a-z]" ./*
}

[ "$#" = 0 ] && todo_list
[ "$1" = t ] && tag_search "$2"
[ "$1" = tl ] && tag_list
[ "$1" = e ] && todo_edit
[ "$1" = s ] && scheduled
[ "$1" = today ] && scheduled_today
[ "$1" = tommorow ] && scheduled_tommorow
