#!/bin/sh

#mac os
printf '%b\n' "\033[1m""uptating dev tools...""\033[0m"
softwareupdate --all --install --force

# homebrew
printf '%b\n' "\033[1m""updating homebrew...""\033[0m"
brew update
brew upgrade --greedy
printf '%b\n' "\033[1m""cleaning up homebrew...""\033[0m"
brew autoremove
brew cleanup

printf '%b\n' "\033[1m""updating vim...""\033[0m"
update-vim-plugins

printf '%b\n' "\033[1m""updating TeX...""\033[0m"
open -a "TeX Live Utility"

# cleanup the trash
printf '%b\n' "\033[1m""cleaning up trash...""\035[0m"
trash -e

# npm
printf '%b\n' "\033[1m""updating npm""\033[0m"
npm update
