#!/bin/sh

USB_DRIVE="/Volumes/UNTITLED"
DRIVE="/Volumes/backup2"
automation=no

check(){
    rsync -av --dry-run "$HOME/.ssh/" "$DRIVE/Ssh Key/" | less
    rsync -av --dry-run "$HOME/Library/Keychains/" "$DRIVE/Keychain/" | less
    rsync -av --dry-run "$DOTFILES/" "$DRIVE/Dotfiles/" | less
    rsync -av --dry-run "$DOCUMENTS/" "$DRIVE/" | less
    rsync -av --progress "$PROJECTS/" "$DRIVE/Projects" | less
    rsync -av --progress "$MEDIA/" "$DRIVE/Media" | less
}

backup_to_disk(){
    printf '%b\n' "\033[1m""Do you wanna go over? [y|n]: ""\033[0m"; read -r ANSWER
    case "$ANSWER" in
         [yY])
            rsync -av --progress "$HOME/.ssh/" "$DRIVE/Ssh Key/"
            rsync -av --progress "$HOME/Library/Keychains/" "$DRIVE/Keychain/"
            rsync -av --progress "$DOTFILES/" "$DRIVE/Dotfiles/"
            rsync -av --progress "$DOCUMENTS/" "$DRIVE/Documents/"
            rsync -av --progress "$PROJECTS/" "$DRIVE/Projects"
            rsync -av --progress "$MEDIA/" "$DRIVE/Media" 
            ;;
         [nN])
            printf "Stoping...\n"
            exit
            ;;
    esac
}

if [ $# = 0 ]; then
    check_usb && exit;
else
  while getopts "adu" opt; do
    case "$opt" in
        a) automation=yes;;
        d) backup_to_disk;;
        u) backup_to_usb;;
    esac
  done
fi
